const testimonialsData = [
  {
    id: 1,
    name: 'Wanjiku Mwangi',
    position: 'CEO, Company',
    testimonial: `I'm thrilled to have found this product. It provides a great opportunity for our kids to learn how to lay a solid foundation in the tech world. Learning to code and ensuring programs work is helping them build crucial digital skills that will be invaluable in the future. Thank you for bringing this solution to our community!`,
    rating: 5,
    image: '/kpsa.jpeg',
  },
  {
      id: 2,
      name: 'Brian Omondi',
      position: 'CEO, Company',
      testimonial: `I've been closely monitoring the progress of our kids since they started taking these classes. It's evident how they're building confidence and technological skills every day. This product is instrumental in empowering our kids to be innovative and tech-savvy.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
      id: 3,
      name: 'Fatma Ali',
      position: 'Manager, Company',
      testimonial: `Through these classes, we've witnessed significant changes in our kids' capabilities. They're not only learning to code but also gaining a deep understanding of computer logic and how technology works.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
    id: 4,
    name: 'Kevin Ochieng',
    position: 'Head of Operations, Tech Firm',
    testimonial: `The impact of these coding classes on our kids has been remarkable. They're not just learning to code; they're learning problem-solving, creativity, and critical thinking. This sets them up for success in a digital world.`,
    rating: 5,
    image: '/kpsa.jpeg',
  },
  {
      id: 5,
      name: 'Aisha Mohammed',
      position: 'Tech Enthusiast',
      testimonial: `As a tech enthusiast, I'm impressed by the curriculum and teaching methods of this program. It's amazing to see kids grasping complex concepts and applying them creatively. This is definitely shaping the future of our tech industry.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
      id: 6,
      name: 'Michael Kamau',
      position: 'Parent',
      testimonial: `Enrolling my child in these coding classes was one of the best decisions I've made. Not only are they learning practical skills, but they're also gaining confidence and independence. It's wonderful to see them excited about learning.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
      id: 7,
      name: 'Sandra Achieng',
      position: 'Educator',
      testimonial: `As an educator, I've seen firsthand the positive impact of integrating coding into the curriculum. It's not just about preparing kids for future careers; it's about equipping them with essential skills for life. This program is paving the way for a brighter future for our children.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
      id: 8,
      name: 'Joseph Gitau',
      position: 'IT Professional',
      testimonial: `Having a background in IT, I understand the importance of early exposure to coding. These classes provide a solid foundation for kids to explore their interests and pursue careers in technology. I'm excited to see the next generation of tech leaders emerging from this program.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
      id: 9,
      name: 'Grace Wangari',
      position: 'School Administrator',
      testimonial: `Integrating coding into our school curriculum has been a game-changer. Not only are the kids engaged and excited about learning, but they're also developing invaluable skills that will set them apart in the future job market. I highly recommend this program to other schools.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
      id: 10,
      name: 'Daniel Mwaura',
      position: 'Software Developer',
      testimonial: `As a software developer, I appreciate the emphasis on both technical skills and creativity in these coding classes. It's inspiring to see kids exploring new ideas and building their own projects. This program is nurturing the next generation of innovators.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
      id: 11,
      name: 'Faith Njeri',
      position: 'Student',
      testimonial: `Taking these coding classes has been an incredible journey for me. Not only have I learned how to code, but I've also gained confidence in my abilities and made new friends who share similar interests. I'm excited to see where this path takes me in the future.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  {
      id: 12,
      name: 'Peter Otieno',
      position: 'Community Leader',
      testimonial: `This program is making a significant difference in our community by providing kids with valuable skills and opportunities. It's empowering them to think critically, solve problems, and pursue their passions in technology. I fully support initiatives like this that invest in our youth.`,
      rating: 5,
      image: '/kpsa.jpeg',
  },
  // More testimonials can be added if needed
];

export default testimonialsData;
