const testimonialsData = [
    {
      id: 1,
      name: 'Wanjiku Mwangi',
      position: 'CEO, Company',
      testimonial: `Great for our kids to learn coding and build digital skills.`,
      rating: 5,
      image: '/woman.svg',
    },
    {
        id: 2,
        name: 'Brian Omondi',
        position: 'CEO, Company',
        testimonial: `These classes empower our kids to be innovative and tech-savvy.`,
        rating: 5,
        image: '/man.svg',
    },
    {
        id: 3,
        name: 'Fatma Ali',
        position: 'Manager, Company',
        testimonial: `Kids gain a deep understanding of technology through these classes.`,
        rating: 5,
        image: '/woman.svg',
    },
    {
      id: 4,
      name: 'Kevin Ochieng',
      position: 'Head of Operations, Tech Firm',
      testimonial: `Remarkable impact on our kids; they're learning problem-solving and critical thinking.`,
      rating: 5,
      image: '/man.svg',
    },
    {
        id: 5,
        name: 'Aisha Mohammed',
        position: 'Tech Enthusiast',
        testimonial: `Impressive curriculum; shaping the future of our tech industry.`,
        rating: 5,
        image: '/woman.svg',
    },
    {
        id: 6,
        name: 'Michael Kamau',
        position: 'Parent',
        testimonial: `Enrolling my child was one of the best decisions; they're gaining confidence and independence.`,
        rating: 5,
        image: '/man.svg',
    },
    {
        id: 7,
        name: 'Sandra Achieng',
        position: 'Educator',
        testimonial: `Essential for equipping kids with skills for life; paving the way for a brighter future.`,
        rating: 5,
        image: '/woman.svg',
    },
    {
        id: 8,
        name: 'Joseph Gitau',
        position: 'IT Professional',
        testimonial: `Solid foundation for kids to explore tech interests; excited to see future tech leaders.`,
        rating: 5,
        image: '/man.svg',
    },
    {
        id: 9,
        name: 'Grace Wangari',
        position: 'School Administrator',
        testimonial: `Game-changer for our school curriculum; kids are engaged and developing invaluable skills.`,
        rating: 5,
        image: '/woman.svg',
    },
    {
        id: 10,
        name: 'Daniel Mwaura',
        position: 'Software Developer',
        testimonial: `Nurturing the next generation of innovators; inspiring to see kids exploring new ideas.`,
        rating: 5,
        image: '/man.svg',
    },
    {
        id: 11,
        name: 'Faith Njeri',
        position: 'Student',
        testimonial: `Incredible journey; gained confidence and made new friends with shared interests.`,
        rating: 5,
        image: '/woman.svg',
    },
    {
        id: 12,
        name: 'Peter Otieno',
        position: 'Community Leader',
        testimonial: `Significant difference in our community; empowering kids to pursue their passions in technology.`,
        rating: 5,
        image: '/man.svg',
    },
  ];
  
  export default testimonialsData;
  